/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.vortex.cli

class App {
    val greeting: String
        get() {
            return """
                ____    ____   ______   .______      .___________. _______ ___   ___ 
                \   \  /   /  /  __  \  |   _  \     |           ||   ____|\  \ /  / 
                 \   \/   /  |  |  |  | |  |_)  |    `---|  |----`|  |__    \  V  /  
                  \      /   |  |  |  | |      /         |  |     |   __|    >   <   
                   \    /    |  `--'  | |  |\  \----.    |  |     |  |____  /  .  \  
                    \__/      \______/  | _| `._____|    |__|     |_______|/__/ \__\ 
                                                                                     
            """.trimIndent()
        }
}

fun main(args: Array<String>) {
    VortexPrinter.printCliDetails()
    VortexPrinter.printTheEnvironments()
}
